[project]
name = "lions"
version = "0.1.0"
description = "Source code for Lions Commentary on Unix"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "plastex>=3.1",
    # Used by scripts/fix-line-refs.py for robust (even on currently malformed) HTML processing
    "beautifulsoup4>=4.12",
]
